### ISSUE TITLE
change recommended test app in readme.md

### ISSUE THREAD

**Issue by offalynne** [jerosoler/snes-gamepad2keyboard#1]
gamepad-tester.com has been loaded with sketchy adware and autoplay ads and is apparently advertising sale of scraped user data

suggest pointing users to https://greggman.github.io/html5-gamepad-test/ or https://apps.nektro.net/gamepad

**Comment by jerosoler** [comment]
Hello @offalynne 

Update Readme! 
 
With adblock it did not show me advertising. 

Thanks!  🕹

Jero
